title = "timlst"
logo = "img/logo.png"
description = "Tim's personal website"
dateFormat = "2 January 2006"
languageCode = "en"

[languages.en.params]
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false


[author]
name = "Tim Leonhard Storm"
image = "img/headshot.jpg"
headline = "Research Intern at CISPA"
bio = "Cool guy"
links = [
{ email = "mailto:me@timlst.de" },
{ pgpkey = "/gpg.key" },
{ github = "https://github.com/timlst/" },
{ linkedin = "https://www.linkedin.com/in/timlst/" },
{ graduation-cap = "https://scholar.google.com/citations?hl=en&user=oIwNhIIAAAAJ" },
# { link = "https://timlst.de" },
#   { discord = "https://discord.gg/invitecode" },
#   { gitlab = "https://gitlab.com/username" },
#   { instagram = "https://instagram.com/username" },
#   { orcid = "https://orcid.org/userid" },
# { reddit = "https://reddit.com/user/username" },
#   { researchgate = "https://www.researchgate.net/profile/username" },
#   { slack = "https://workspace.url/team/userid" },
#   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#   { steam = "https://steamcommunity.com/profiles/userid" },
#   { twitter = "https://twitter.com/username" },
#   { whatsapp = "https://wa.me/phone-number" },
]
