title = "timlst"
weight = 1

[languages.en]
locale = "en"
label = "English"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Tim's personal website"
logo = "img/logo.jpg"

[[params.author.links]]
email = "tim@diestorms.de"

[[params.author.links]]
github = "https://github.com/timlst"

[[params.author.links]]
graduation-cap = "https://scholar.google.com/citations?user=oIwNhIIAAAAJ&hl=de"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/timlst/"

[[params.author.links]]
pgpkey = "/gpg/"

[author]
name = "Tim Leonhard Storm"
image = "img/headshot.jpg"
headline = "Incoming PhD Student at CISPA"
bio = "Cool guy"

  [[author.links]]
  email = "mailto:me@timlst.de"

  [[author.links]]
  pgpkey = "/gpg/"

  [[author.links]]
  github = "https://github.com/timlst/"

  [[author.links]]
  linkedin = "https://www.linkedin.com/in/timlst/"

  [[author.links]]
  graduation-cap = "https://scholar.google.com/citations?hl=en&user=oIwNhIIAAAAJ"

["params.author"]
name = "Tim Storm"
email = "tim@diestorms.de"
image = "headshot.jpg"
imageQuality = ""
headline = "Incoming PhD Student @ CISPA"
bio = "cool guy"
