languageCode = "de"
languageName = "Deutsch"
displayName = "DE"
isoCode = "de"
weight = 2
rtl = false

title = "timlst"
# logo = "img/logo.png"
description = "Tims coole Webseite"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2. January 2006"

[author]
  name = "Tim Storm"
  image = "img/headshot.gif"
  headline = "Ich hab in New York gelebt, ich weiß was ein Bähgl ist"
  bio = "Cooler Typ"
  links = [
    { github = "https://github.com/timlst/" },
    { email = "mailto:me@timlst.de" },
    { pgpkey = "/pgp.txt" },
    # { link = "https://timlst.de" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { instagram = "https://instagram.com/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { orcid = "https://orcid.org/userid" },
    # { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  ]
